### PR TITLE
More metadata (and adapted links)

### PR DESCRIPTION
**Pull request by MarcelWaldvogel**
- Include OpenGraph metadata
- Made sure that Jekyll links work (x.html -> /x/)

### CODE REVIEW

**Comment by sualko** [comment]
> Made sure that Jekyll links work (x.html -> /x/)

Why did you rename all links? Doesn't make sense to me and it's also bad for SEO.

**Comment by MarcelWaldvogel** [comment]
`jekyll serve --watch` did not work without it (dead links).

**Comment by MarcelWaldvogel** [comment]
If your Jekyll works with the /x.html names (mine does not), here's a version with the old naming scheme (with absolute links instead of relative, but that should not be a problem)

**Comment by sualko** [comment]
fixed with https://github.com/jsxc/jsxc.org/commit/05cb4e4e138032119dda048376644fe4d1a49ff4

**Pull request closed without merging**
